### ISSUE TITLE
Failed to match/Unable to decrypt NCA header

### ISSUE THREAD

**Issue by verbes4** [Thealexbarney/LibHac#251]
See screenshot below
![Untitled](https://user-images.githubusercontent.com/24574201/175812133-81a70dbc-508b-4e1a-8c40-74e648524086.png)
No idea what the issue is, I have the keys as you can see in Notepad, so I don't know why it wont decrypt. I have title.keys and dev.keys too, literally just dumped them from my Switch with lockpick

**Comment by DarkMatterCore** [comment]
@verbes4 `Failed to match x` warnings are completely normal, and they appear because either `prod.keys` or `dev.keys` (depending on whether `-d` is used or not) holds key entries that are unsupported/unused by hactoolnet. You can silence these warnings by using `--disablekeywarns`.

Assuming you used the latest Lockpick_RCM release to get these keys, you're most likely dealing with a corrupted NCA file.

**Comment by verbes4** [comment]
oh okie, thank you very much
