### ISSUE TITLE
Suspicious code in Nca.OpenAesCtrExStorage

### ISSUE THREAD

**Issue by DCNick3** [Thealexbarney/LibHac#280]
This code in `Nca.OpenAesCtrExStorage` is sus:

https://github.com/Thealexbarney/LibHac/blob/1e421a36ae6cfde1d153b5c987fa10092378f343/src/LibHac/Tools/FsSystem/NcaUtils/Nca.cs#L302-L303

It uses `IndirectStorage.QueryEntryStorageSize` for reading `OpenAesCtrEx` bucket tree. This doesn't seem correct, as `IndirectStorage` and `Aes128CtrExStorage` have different entry sizes (0x14 vs 0x10) and leads to incorrect (larger) value of `entryStorageSize`.

Maybe it's a copy-paste error?

**Comment by Thealexbarney** [comment]
You're correct about it being an error. The reason `QueryNodeStorageSize` still works is because the entry size only comes into play when there are too many entry sets (the entries located in the entry storage) for the offset nodes (the offsets located in the node storage) to fit into a 0x4000-byte block. When this happens, the bucket tree gains an additional level to the tree, making the node storage take up more space than a single block. The size of the entry is needed to calculate how many blocks are needed for the node storage.

`QueryEntryStorageSize` works because the `IndirectStorage` entry is larger than the `AesCtrCounterExtendedStorage` entry. This means the created `SubStorage` still covers the entire entry storage, it just extends past the end a bit. `BucketTree` doesn't care about this because it doesn't care if the entry storage is larger than is necessary to hold all the entries.

**Comment by DCNick3** [comment]
Btw, do you know of any games that have this additional layer in the AesCtrEx bucket tree (or any bucket tree, really)? I've been trying to test my code for that, but didn't have any luck finding a game that has NCAs with these "extended" bucket trees

**Comment by Thealexbarney** [comment]
There aren't any games that have any bucket trees with L2. None of them even come close. You need somewhere in the vicinity of a couple hundred thousand entries before you need the additional layer.

You could use the bucket tree builder in LibHac to generate larger trees. LibHac's `BucketTree` and `IndirectStorage` tests use this builder to generate trees of various sizes

**Comment by Thealexbarney** [comment]
Fixed by 04a5d03b
