### ISSUE TITLE
--sign and --repack when using -t save

### ISSUE THREAD

**Issue by dhow** [Thealexbarney/LibHac#96]
I was testing the `--sign` and `--repack` options for `-t save`. I'm not quite sure how they work and the expected behavior, if anyone could shed some light, that would be great. (-; 

1. By repacking the size of the save data will not go beyond the Save Data Size -- is this normal? FYI, I tried to add a few files in the directory so the size will be 3 times bigger than the original save, however the resulting save is still the same size as original. 

2. When I `--repack` the save, from `--listfiles` I can see that CMAC Signature and Header Hash are changed in the packed save. But when I `--sign --repack` the signature and hash are the same. What's the the use case of `--sign`?

3. Even if I `--repack` without data changed, the MAC Signature and Header Hash are changed in the repacked save, should I expect that the save shall be treated as a legitimate save? 

Thanks! 

P.S.: Using hactoolnet v0.6.0

**Comment by Thealexbarney** [comment]
1. All the space in the savedata is preallocated, so removing or adding files won't change the size of it. Once you run out of free space in the save you can't add any more files to it.

2. `--sign` can be used when you want to resign the savedata for use on a different console without modifying it.

3. The save will be legitimate. The layout of the filesystem can change when you delete all the files and recreate them because the order in which the files are added affects the layout.

**Comment by dhow** [comment]
Crystal clear, thanks so much @Thealexbarney !
